<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('profiles', function (Blueprint $table) { $table->id(); $table->foreignId('user_id')->unique()->constrained()->cascadeOnDelete(); $table->string('job_title')->nullable(); $table->string('company')->nullable(); $table->text('bio')->nullable(); $table->string('phone', 40)->nullable(); $table->string('whatsapp', 40)->nullable(); $table->string('website')->nullable(); $table->string('address')->nullable(); $table->string('city')->nullable(); $table->string('country', 2)->nullable(); $table->string('timezone')->default('Asia/Dhaka'); $table->json('settings')->nullable(); $table->timestamps(); });
        Schema::create('themes', function (Blueprint $table) { $table->id(); $table->string('name'); $table->string('slug')->unique(); $table->text('description')->nullable(); $table->string('preview_image')->nullable(); $table->json('schema')->nullable(); $table->boolean('is_premium')->default(false); $table->boolean('is_active')->default(true)->index(); $table->unsignedSmallInteger('sort_order')->default(0); $table->timestamps(); });
        Schema::create('vcards', function (Blueprint $table) { $table->id(); $table->foreignId('user_id')->constrained()->cascadeOnDelete(); $table->foreignId('theme_id')->nullable()->constrained()->nullOnDelete(); $table->string('name'); $table->string('slug')->unique(); $table->string('job_title')->nullable(); $table->string('company')->nullable(); $table->text('about')->nullable(); $table->string('phone', 40)->nullable(); $table->string('whatsapp', 40)->nullable(); $table->string('email')->nullable(); $table->string('website')->nullable(); $table->string('location')->nullable(); $table->string('status')->default('draft')->index(); $table->boolean('is_published')->default(false)->index(); $table->boolean('available_for_work')->default(false); $table->json('seo')->nullable(); $table->json('settings')->nullable(); $table->timestamp('published_at')->nullable(); $table->timestamps(); });
        Schema::create('social_links', function (Blueprint $table) { $table->id(); $table->foreignId('vcard_id')->constrained()->cascadeOnDelete(); $table->string('platform', 40); $table->string('url'); $table->string('username')->nullable(); $table->boolean('is_visible')->default(true); $table->unsignedSmallInteger('sort_order')->default(0); $table->timestamps(); $table->index(['vcard_id','is_visible']); });
        Schema::create('payment_methods', function (Blueprint $table) { $table->id(); $table->foreignId('vcard_id')->constrained()->cascadeOnDelete(); $table->string('provider', 50); $table->string('label')->nullable(); $table->string('account_name')->nullable(); $table->string('account_number')->nullable(); $table->text('instructions')->nullable(); $table->text('metadata')->nullable(); $table->boolean('is_visible')->default(true); $table->unsignedSmallInteger('sort_order')->default(0); $table->timestamps(); });
        Schema::create('services', function (Blueprint $table) { $table->id(); $table->foreignId('vcard_id')->constrained()->cascadeOnDelete(); $table->string('title'); $table->text('description')->nullable(); $table->decimal('price', 12, 2)->nullable(); $table->string('currency', 3)->default('USD'); $table->string('cta_url')->nullable(); $table->boolean('is_visible')->default(true); $table->unsignedSmallInteger('sort_order')->default(0); $table->timestamps(); });
        Schema::create('portfolios', function (Blueprint $table) { $table->id(); $table->foreignId('vcard_id')->constrained()->cascadeOnDelete(); $table->string('title'); $table->string('category')->nullable(); $table->text('description')->nullable(); $table->string('project_url')->nullable(); $table->date('completed_at')->nullable(); $table->boolean('is_visible')->default(true); $table->unsignedSmallInteger('sort_order')->default(0); $table->timestamps(); });
        Schema::create('galleries', function (Blueprint $table) { $table->id(); $table->foreignId('vcard_id')->constrained()->cascadeOnDelete(); $table->string('title')->nullable(); $table->text('caption')->nullable(); $table->boolean('is_visible')->default(true); $table->unsignedSmallInteger('sort_order')->default(0); $table->timestamps(); });
        Schema::create('cv_files', function (Blueprint $table) { $table->id(); $table->foreignId('vcard_id')->constrained()->cascadeOnDelete(); $table->string('label')->default('Resume'); $table->string('version')->nullable(); $table->boolean('is_active')->default(true); $table->unsignedBigInteger('download_count')->default(0); $table->timestamps(); });
    }
    public function down(): void
    {
        Schema::dropIfExists('cv_files'); Schema::dropIfExists('galleries'); Schema::dropIfExists('portfolios'); Schema::dropIfExists('services'); Schema::dropIfExists('payment_methods'); Schema::dropIfExists('social_links'); Schema::dropIfExists('vcards'); Schema::dropIfExists('themes'); Schema::dropIfExists('profiles');
    }
};
